### ISSUE TITLE
Invariant Violation: Module  is not a registered callable module (calling onMessage)

### ISSUE THREAD

**Issue by BPich** [reggie3/react-native-webview-leaflet#140]
Hi !

I'm trying to run a basic map following the [readme steps](https://github.com/reggie3/react-native-webview-leaflet#usage) but get the following error : 
`Invariant Violation: Module  is not a registered callable module (calling onMessage)`

The App.js to reproduce the error : 
```
import React from 'react';
import { WebViewLeaflet } from "react-native-webview-leaflet";

export default function App() {
  return (
    <WebViewLeaflet
      ref={component => (this.webViewLeaflet = component)}
    />
  );
}
```

I saw some similar issues (with no definitive answer) on the [react-native-webview github](https://github.com/react-native-webview/react-native-webview) project ([#1573](https://github.com/react-native-webview/react-native-webview/issues/1573), [#1324](https://github.com/react-native-webview/react-native-webview/issues/1324))

Using 
- expo 4.12.0
- npm 6.14.12
- react-native ~0.63.4
- react-native-webview-leaflet ^5.0.2

Testing on my android device

Thanks for your help !

**Comment by miallo** [comment]
Did you run `npm run ios` or `npm run android`? BTW, this repository is no longer maintained, but there is a fork on [pavel-corsaghin/react-native-leaflet](https://github.com/pavel-corsaghin/react-native-leaflet) published under `react-native-leaflet-view` with most features, but noticeably better code quality

**Comment by BPich** [comment]
I used the Expo Go app to run it on my physical device (Android). 
Didn't know this repo was obsolete, will check on the project you're pointing to, hopefully the issue won't appear there. 
Thanks !
