### ISSUE TITLE
How do I load the map

### ISSUE THREAD

**Issue by xiaoliyong** [reggie3/react-native-webview-leaflet#17]
Can you write a detailed tutorial？

**Comment by reggie3** [comment]
Did you check out the readme on this repo?  I tried to be very explicit on how to use the component.  Let me know what is not clear about it.

**Comment by xiaoliyong** [comment]
`  <WebViewLeaflet
              // get a reference to the web view so that messages can be sent to the map
              ref={(component)=> (this.webViewLeaflet = component)}
              // the component that will receive map events
              eventReceiver={this}
          />`
I use it, but not show a map in my android Emulator
and show a error
### Emulator: CANNOT TRANSLATE guest DNS ip

**Comment by reggie3** [comment]
Thanks for the quick response.
You are using the component correctly.  The error you received is network related so I'd start by confirming that the emulator has network access as this stackoverflow article suggests. [](https://stackoverflow.com/questions/42526466/how-to-prevent-android-studio-avd-cannot-translate-guest-dns-ip-error-messag)

**Comment by xiaoliyong** [comment]
Thanks for your answer.
If i want to load a map from Open Street Maps, how can i load it?
I don't see you loading a map using URL in your component.

**Comment by reggie3** [comment]
The Open Street Map tiles will be loaded by default.  You can see the code for loading it in the leafletComponent.js file

**Comment by xiaoliyong** [comment]
sorry，I don't find leafletComponent.js, 
Which folder is it in?

**Comment by reggie3** [comment]
it is in the 'src/web' folder
