### ISSUE TITLE
No map in the finished apk.

### ISSUE THREAD

**Issue by atkisai** [reggie3/react-native-webview-leaflet#19]
During the development of the tile map there, but there is no tile map for the finished apk. 
There is only a button.
Tile map dont run without comand "react-native run-android" on the development device.
Tile map dont run in finished apk.
I dont now why is this.
![screenshot_1](https://user-images.githubusercontent.com/25017486/42324107-d761dba2-806a-11e8-9c07-9975ba9f64d1.png)

**Comment by reggie3** [comment]
I've never tried to run the package using the` react-native run-android` command.  Can you post your code?

**Comment by reggie3** [comment]
This is a tough one.  Are you sure you have a network connection?  The map tiles are not included in the library, and must be streamed to the device.

**Comment by GabrielScalici** [comment]
> I run into this problem.
> Everything works fine in development mode:
> 
> * My dev environment is Linux
> * App created with: react-native init
> * Run in dev with: react-native run-android
> 
> After created my apk with:
> 
> ```
> $ react-native bundle --dev false --platform android --entry-file index.js --bundle-output ./android/app/build/intermediates/assets/debug/index.android.bundle --assets-dest ./android/app/build/intermediates/res/merged/debug
> $ cd android && ./gradlew assembleDebug
> ```
> Moved the apk to Android device and installed.
> It says it is not trusted but I installed anyway.
> 
> After open, no tiles. But I can see it respondes to zoom and map navigation.
> 
> Any ideas for debugging? Thanks.

Same issue, and I have a network connection.

**Comment by reggie3** [comment]
@GabrielScalici I'm assuming the map works in the dev environment.  I have't tried to publish an actual APK yet, so I haven't run into this problem.
Hopefully, somebody else can speak more towards a solution.

**Comment by reggie3** [comment]
This issue has been moved to issue #33
