### ISSUE TITLE
trying to add custom map

### ISSUE THREAD

**Issue by suraj740** [reggie3/react-native-webview-leaflet#20]
Hi @reggie3 ,
i am trying to add custom map in place of default open street maps , then how can i set markers on that.
Please help if possible

**Comment by reggie3** [comment]
I've never tired to add another map tile set. What tile set are you using?

**Comment by suraj740** [comment]
@reggie3 thanks for reply,
i am trying to use 2d mall map in place of that.

**Comment by reggie3** [comment]
I'm not sure that is possible. Have you taken a look at the original
leaflet library to see if it is possible there? My library card do anything
the original can't.  However, if you can figure out how to get it working
with leaflet, then I think I can get something working.

**Comment by marconett** [comment]
trying to do the same at the moment. there's a tutorial for vanilla leafletjs: https://leafletjs.com/examples/crs-simple/crs-simple.html

**Comment by suraj740** [comment]
Hi @reggie3, i have already created that using leaflet and is working for web. But the thing is that i want to use that in react native. Can you help now if possible.

**Comment by reggie3** [comment]
closing this and moving it to #24

**Comment by hussainahmad** [comment]
@reggie3  
``` {
        name:'Yandex Satellite',
        type:'TileLayer',
        baseLayer: true,
        url:"https://sat02.maps.yandex.net/tiles?l=sat&z={z}&x={x}&y={y}&scale=2&lang=en_US",
        attribution:'&copy; <a href="https://yandex.com/maps/">Yandex</a>'
    },
```
with above map tile layer url you can easily find this issue.  to resolve this I have to pass  `crs = L.CRS.EPSG3395` , don't know how to this, as found minimal support for customization.
