### ISSUE TITLE
Image Overlay using Leaflet

### ISSUE THREAD

**Issue by jiashenglim** [reggie3/react-native-webview-leaflet#21]
Hi, Thanks for sharing. I am trying to implement a floorplan with marker for using leaflet to react native.
Something similar to this ...https://codepen.io/zachdunn/pen/VvRXdP 
Will I be able to implement it with your library

**Comment by reggie3** [comment]
This library is built on top of the react-leaflet library, so if you can get it working with that library, then I think it could be made to work here.  If you look at the react-leaflet imageOverlay documentation here [](https://react-leaflet.js.org/docs/en/components.html#imageoverlay) then what you're looking for should be possible by replacing the TileLayer component in the mapComponent.js file.

**Comment by reggie3** [comment]
For question #1, you can edit the MapComponent.js file in this package's node_modules directory in your project.  That'll get you to the point of at least making it work for you.  You could also fork this repo, make changes to your copy, and then install from your fork.  Here is a short article on that subject [](https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a)

I'd want to figure out a way to generalize what you're doing to cover the other types of raster layers that are available. They are listed here: [](https://react-leaflet.js.org/docs/en/components.html#raster-layers)

Below is one approach if you are interested in submitting a pull request to add the functionality you want to this package.

Tilelayer is already implemented in this library, and the URL prop is hard coded to Open Street Maps.  This library would need a way to identify what kind of Layer Component the user wants to use.  This could be based on a specific "Layer" prop that is given to the WebViewLeaflet component along with the appropriate props for that type of layer.  Then the MapComponent can render the appropriate layer based on those props.

**Comment by reggie3** [comment]
closing this and moving it to #24
