### ISSUE TITLE
Adding an URL parameter to the Component to use a custom TileLayer

### ISSUE THREAD

**Issue by Kroonax** [reggie3/react-native-webview-leaflet#24]
Hello,

First, thanks for working on this package, I've been hurting my head for a long time to make an Expo app work with a Map package that is not Google Maps (you now, Maps pricing changed...).

This issue kind of adresses #21 , it would be REALLY cool it it were possible to add a simple URL to the component to use a custom TileLayer. I am used to work with some techs from a company that provides custom TileLayers and I would be so thrilled to use them in my new project !

Tell me if you have the time to implement this, if you don't, I'd be glad to help you and submit a PR, problem is I don't have that much free time nowadays.

Thanks in advance and good job for the great work,

**Comment by reggie3** [comment]
I'm working on that right now, and hope to have something done soon.  This feature will be in the `6-with-raster-layers-2` branch.

**Comment by reggie3** [comment]
Starting with 3.0.15 I've gotten multiple raster layers and WMSTileLayer to work.  Still no luck with Image and Video Overlays.

**Comment by lchnnl** [comment]
Hi Reggie3. We managed to use a different coordinate system using your library as a starting point. I believe leaflet uses (by default) EPSG:4326 coordinate system, however when you want to use a different coordinate system, you'll have to use the Proj4 and proj4Leaflet libraries to add different coordinate systems.
