### ISSUE TITLE
Map didn't show

### ISSUE THREAD

**Issue by tritonjoyeux** [reggie3/react-native-webview-leaflet#25]
Hi, 
I followed the README and my map is not showing :/ 
![image](https://user-images.githubusercontent.com/16247113/43578620-9507b592-964f-11e8-9a42-8efdf033e5c8.png)
Render =>
 ```
<View style={styles.container}>
   <WebViewLeaflet
      ref={(component) => (this.webViewLeaflet = component)}
      eventReceiver={this}
   />
</View>
```

**Comment by Kroonax** [comment]
That little snippet of code does not really help, is it a "vanilla" App.js file ?

Having your whole code sample would help a lot

**Comment by marioviana** [comment]
@tritonjoyeux Probably that's because you put that component inside View. 

Try to remove the View component.

**Comment by reggie3** [comment]
Also, make sure you have the correct styles for `styles.container`
See the example in `App.js` for more detail.

**Comment by tritonjoyeux** [comment]
It works @marioviana thanks :)
