### ISSUE TITLE
Viewport doesn't work

### ISSUE THREAD

**Issue by CdRom1** [reggie3/react-native-webview-leaflet#26]
Hello!
I am able to update the viewport using react-leaflet bounds like this:
```
this.webViewLeaflet.sendMessage({
    bounds: [[49.41550, 2.81865], [49.41552,2.81867]],
});
```
This code works perfectly and doesn't print anything to the console.

But I can't use the viewport API. This code doesn't seem to do anything except printing a message to the console.
```
this.webViewLeaflet.sendMessage({
			viewport: {
				center:[49.41551,2.81866],
				zoom:19
			}
});
```
The viewport api would be a very useful tool because it uses the same formatting than geo urls...
Thanks,
Romain

**Comment by CdRom1** [comment]
I've just realized the zoom property works like this, but not the center property:
```
this.webViewLeaflet.sendMessage({
			center:[49.41551,2.81866],
			zoom:19

});
```

**Comment by reggie3** [comment]
Were you able to solve your issue?

**Comment by CdRom1** [comment]
No, so my workaround was to convert the desired center/zoom into bounds, using sample code from leaflet.

**Comment by reggie3** [comment]
Sounds good.  I'm going to close this issue then.
