### ISSUE TITLE
Marker - Icon Anchor

### ISSUE THREAD

**Issue by plSln** [reggie3/react-native-webview-leaflet#27]
Hello,
I have to add the Icon Anchor to a Marker, Leaflet supports that:
https://leafletjs.com/examples/custom-icons/

How can I add it?

```
locations: [{
              name: 'positionMarker',
              icon: '<img src="../../../../assets/icons/position.png" width="100" height="100" >',
              coords: [position.coords.latitude, position.coords.longitude],
              size: [100, 100],
              iconAnchor:   [22, 94],
            }]

```
Best regards & thanks for your help, 
Philipp

**Comment by reggie3** [comment]
Starting at version 3.0.15, I added an `iconAnchor` property that you can set on the location object.  Please let me know if it is what you're looking for.
