### ISSUE TITLE
Can't Goto My Location on Map Start

### ISSUE THREAD

**Issue by wresniwahyu** [reggie3/react-native-webview-leaflet#30]
I am new in react native and i want to show map in my app use osm and i found this cool library. i was read and copy from your App.js code, i am not use expo for get location. 
How to goto my location automatically when map start if i had coordinate ? 
and how to active button my location and zoom in out in map?
Can anyone help me? thanks before bro for this cool lib

`import React, { Component } from 'react';
import { ScrollView, StyleSheet, Text, View, Platform, Alert } from 'react-native';
import { Container, Button, Item, Input, Content } from 'native-base';
import { Grid, Row, Col } from "react-native-easy-grid";
import Spinner from 'react-native-loading-spinner-overlay';
import WebViewLeaflet from 'react-native-webview-leaflet';
import styles from './styles'

export default class Status extends Component {
    constructor() {
        super();
        this.state = {
            location: null,
            errorMessage: null,
            coords: undefined,
            showEmojiSelectorModal: false,
            mapState: {
                showAttributionControl: false,
                showZoomControls: false,
                panToLocation: false,
                zoom: 10
            },
            myLoc: [-6.240343, 106.802693],
        };
    }

    static navigationOptions = {
        title: 'Status',
        headerTitleStyle: {
            flex: 1,
            textAlign: 'center',
            alignSelf: 'center'
         },
         headerStyle: {
            backgroundColor: '#2a2723',
          },
        headerTintColor: '#fff',
    }

    componentWillMount() {
        this.geCurrenttLatLong();
        
    }

    componentDidMount() {
        setTimeout(() => {
            console.log('LatLong => '+this.state.coords);
        }, 1000);
    }

    showAlert = (title, body) => {
        Alert.alert(
          title,
          body,
          [{ text: 'OK', onPress: () => console.log('OK Pressed') }],
          { cancelable: false }
        );
      };

    geCurrenttLatLong(){
        this.watchID = navigator.geolocation.watchPosition((position) => {
              let region = {
                latitude:       position.coords.latitude,
                longitude:      position.coords.longitude,
              }
                this.setState({
                    coords: region.latitude+','+region.longitude
                });
                console.log('latlong => '+this.state.coords);
            });
    }

    componentDidUpdate = (prevProps, prevState) => {
        // do these things once the map has loaded
        if (!prevState.mapState.mapLoaded && this.state.mapState.mapLoaded) {
          this.webViewLeaflet.sendMessage({
            zoom: 6,
            locations: this.state.locations,
            showAttributionControl: this.state.mapState.showAttributionControl,
            showZoomControl: this.state.mapState.showZoomControl
          });
        }
    
        // do these things only if the map has been loaded
        if (this.state.mapState.mapLoaded) {
          // if the user's location has changed
          if (prevState.coords !== this.state.coords) {
            this.webViewLeaflet.sendMessage({
              centerPosition: this.state.coords,
    
              locations: [
                ...this.state.locations,
                {
                  id: 0,
                  coords: this.state.coords,
                  icon: '❤️',
                  size: [24, 24],
                  animation: {
                    name: 'pulse',
                    duration: '.5',
                    delay: 0,
                    interationCount: 'infinite'
                  }
                }
              ]
            });
          }
        }
      };
    

    onMapClicked = ({ payload }) => {
        console.log(`Map Clicked: app received: ${payload.coords}`);
        this.showAlert('Map Clicked', `Coordinates = ${payload.coords}`);
    };

render() {
        return (
            
                
                <Container style={styles.container}>
                    <Grid style={{flex:1, flexDirection: 'column'}}>
                        <View style={{flex:1.15}}>                            
                            <WebViewLeaflet style={styles.absolute_map}
                                ref={(component) => (this.webViewLeaflet = component)}
                                eventReceiver={this}
                            />
                            <Item regular style={styles.absolute_search}>
                                <Input placeholder='Cari lokasi...'/>
                            </Item>
                        </View>
                        <View style={{flex:0.85, flexDirection: 'column'}}>
                            <ScrollView style={{width: '100%', height: '100%', padding: 5}}>
                                {/* <View style={{ flex: 1 }}>
                                    <Spinner visible={this.state.loading}/>
                                </View> */}
                                <Content>
                                    <Text style={{color: 'white'}}>TES tES TES</Text>
                                    <Text style={{color: 'white'}}>TES tES TES</Text>
                                    <Text style={{color: 'white'}}>TES tES TES</Text>
                                    <Text style={{color: 'white'}}>TES tES TES</Text>
                                    <Text style={{color: 'white'}}>TES tES TES</Text>
                                    <Text style={{color: 'white'}}>TES tES TES</Text>
                                    <Text style={{color: 'white'}}>TES tES TES</Text>
                                    <Text style={{color: 'white'}}>TES tES TES</Text>
                                </Content>
                            </ScrollView>
                        </View>
                    </Grid>
                </Container>
        );
    }
}`

**Comment by wresniwahyu** [comment]
@marioviana thanks it works in emulator but in ios device i get error 
"Possible Unhandled Promise Rejection(id: 0) Error to open URL..."

what should i do?

**Comment by reggie3** [comment]
@wresniwahyu I just did some updates that may fix the problem you ran into.  Download the latest version and try it again.  Also, make sure you have a good network connection.  

I've confirmed that the current demo app works on an iPhone 6+.  Why don't you try copying the code from the demo App and see if you get the same error.

**Comment by gisert** [comment]
Im so  sorry for interrupting you, what should I do

**Comment by reggie3** [comment]
You'll need to post the code you're using.

**Comment by wresniwahyu** [comment]
> @wresniwahyu I just did some updates that may fix the problem you ran into. Download the latest version and try it again. Also, make sure you have a good network connection.
> 
> I've confirmed that the current demo app works on an iPhone 6+. Why don't you try copying the code from the demo App and see if you get the same error.

@reggie3 Oke thanks now it work in real device.
I want to try with your code but i get some error because iam not using expo maybe.

Now I am stuck with add some marker
I am try copy your App.js code but there is no marker added

Can u show me the simplest way to add markers in map?

**Comment by wresniwahyu** [comment]
> @wresniwahyu I just did some updates that may fix the problem you ran into. Download the latest version and try it again. Also, make sure you have a good network connection.
> 
> I've confirmed that the current demo app works on an iPhone 6+. Why don't you try copying the code from the demo App and see if you get the same error.

@reggie3 Oke thanks now it work in real device.
I want to try with your code but i get some error because iam not using expo maybe.

but i have same problem again
i've set function to get lat lng in componentDidMount()
and then send message to webview

sometimes it work to animate goto center map
but often its not work

you can see in the log i get the latlong before sending message to webview but animate map to center not work

**LOG**
![screen shot 2018-09-20 at 12 59 27 pm](https://user-images.githubusercontent.com/43021166/45798933-ed4b6f80-bcd5-11e8-9c75-d3832b1ab4b0.png)

**this is my code**


`componentDidMount() {
        this.geCurrenttLatLong();
    }`

`geCurrenttLatLong(){
        // if (hasLocationPermission) {
            Geolocation.getCurrentPosition(
                (position) => {
                    console.log(position);

                    let region = {
                        latitude: position.coords.latitude,
                        longitude: position.coords.longitude,
                        latlong: position.coords.latitude+','+position.coords.longitude,
                    }

                    this.setState({
                        latitude: region.latitude,
                        longitude: region.longitude,
                        coords: region.latitude+','+region.longitude,
                    }); 

                    console.log('latlong method => '+this.state.coords);
                        
                    this.webViewLeaflet.sendMessage({
                        zoom: 15,
                        showAttributionControl: this.state.mapState.showAttributionControl,
                        showZoomControl: this.state.mapState.showZoomControl,
                        centerPosition: { lat: region.latitude, lng: region.longitude },
                    })   


                },
                (error) => {
                    // See error code charts below.
                    console.log(error.code, error.message);
                },
                { enableHighAccuracy: true, timeout: 15000, maximumAge: 10000 }
            );
}`

**Comment by wresniwahyu** [comment]
> > @wresniwahyu I just did some updates that may fix the problem you ran into. Download the latest version and try it again. Also, make sure you have a good network connection.
> > I've confirmed that the current demo app works on an iPhone 6+. Why don't you try copying the code from the demo App and see if you get the same error.
> 
> @reggie3 Oke thanks now it work in real device.
> I want to try with your code but i get some error because iam not using expo maybe.
> 
> but i have same problem again
> i've set function to get lat lng in componentDidMount()
> and then send message to webview
> 
> sometimes it work to animate goto center map
> but often its not work
> 
> you can see in the log i get the latlong before sending message to webview but animate map to center not work
> 
> **LOG**
> ![screen shot 2018-09-20 at 12 59 27 pm](https://user-images.githubusercontent.com/43021166/45798933-ed4b6f80-bcd5-11e8-9c75-d3832b1ab4b0.png)
> 
> **this is my code**
> 
> `componentDidMount() { this.geCurrenttLatLong(); }`
> 
> `geCurrenttLatLong(){
> // if (hasLocationPermission) {
> Geolocation.getCurrentPosition(
> (position) => {
> console.log(position);
> 
> ```
>                 let region = {
>                     latitude: position.coords.latitude,
>                     longitude: position.coords.longitude,
>                     latlong: position.coords.latitude+','+position.coords.longitude,
>                 }
> 
>                 this.setState({
>                     latitude: region.latitude,
>                     longitude: region.longitude,
>                     coords: region.latitude+','+region.longitude,
>                 }); 
> 
>                 console.log('latlong method => '+this.state.coords);
>                     
>                 this.webViewLeaflet.sendMessage({
>                     zoom: 15,
>                     showAttributionControl: this.state.mapState.showAttributionControl,
>                     showZoomControl: this.state.mapState.showZoomControl,
>                     centerPosition: { lat: region.latitude, lng: region.longitude },
>                 })   
> 
> 
>             },
>             (error) => {
>                 // See error code charts below.
>                 console.log(error.code, error.message);
>             },
>             { enableHighAccuracy: true, timeout: 15000, maximumAge: 10000 }
>         );
> ```
> }`

Hi @reggie3 can u help my issue above ?

**Comment by reggie3** [comment]
I don't know where the websocket error is coming from since this library doesn't use it.
