### ISSUE TITLE
Package does not work in published Android APK

### ISSUE THREAD

**Issue by reggie3** [reggie3/react-native-webview-leaflet#33]
This package does not work in published APK.
This issue also affects react-native-webview-quilljs.

Efforts to fix this problem affecting both packages will be tracked here

**Comment by reggie3** [comment]
Using the fix suggested by use @ide in the above Expo forum thread seems to solve the problem.  The beta that incorporates this fix can be installed using `yarn add react-native-webview-leaflet@beta` (or npm install if you prefer)

So far, the only negative effect that I have found is that the Leaflet map layer control buttons do not have icons on them.

**Comment by reggie3** [comment]
While this current beta works in production on Android, I still need someone to confirm that it works on iOS.  I would appreciate it if somebody could try it and let me know.  

First, you'd need to have Expo installed
Then you'll have to clone this repo, and specifically clone the '10-without-sentry-logging' branch.
Assuming you've done both of those, edit the `app.json` file's `bundleIdentifier` value to something unique like com.[your user name].reactnativewebviewleaflet
Then you'll need to build a standalone package (called an IPA in iOS).  Expo details that process here: https://docs.expo.io/versions/v30.0.0/distribution/building-standalone-apps

You'll then need to built package the program on your device.  HOwever, I am not familiar with how that works in iOS.

**Comment by zahid49** [comment]
> Using the fix suggested by use @ide in the above Expo forum thread seems to solve the problem. The beta that incorporates this fix can be installed using `yarn add react-native-webview-leaflet@beta` (or npm install if you prefer)
> 
> So far, the only negative effect that I have found is that the Leaflet map layer control buttons do not have icons on them.

Hi @reggie3, did you manage to make it work (those "layer control buttons") ?
