### ISSUE TITLE
No rendering markers

### ISSUE THREAD

**Issue by skyflystar** [reggie3/react-native-webview-leaflet#38]
How can I render markers on map?
I have code below, but it shows only yellow screen.
```                    
<WebViewLeaflet
  ref={(component) => (this.webViewLeaflet = component)}
  onLoad={this.onLoad}
  eventReceiver={this}
  mapLayers={[{
    name: 'streets',
    checked: 'true',
    type: 'TileLayer',
    baseLayer: true,
    url: 'https://api.tiles.mapbox.com/v4/mapbox.streets/{z}/{x}/{y}.png?access_token=${MY_API_KEY}',
  }]}
   markers={[{
    coords: [37.06452161, -75.67364786],
    icon: "❤️",
    id: 0,
   }]}
/>
```

I think a reason in markers prop. When I deleted it, map works fine.

**Comment by gus3inov** [comment]
Are you sure that your mapLayres doesn't conflict with markers ?
Just try remove mapLayers for example

**Comment by gus3inov** [comment]
Ant try to set ownPositionMarker, i think its required for markers

**Comment by skyflystar** [comment]
Removing mapLayers is incompatible. Setting ownPositionMarker didn't help :(

**Comment by skyflystar** [comment]
@reggie3 need your help

**Comment by skyflystar** [comment]
> 
> 
> How can I render markers on map?
> I have code below, but it shows only yellow screen.
> 
> ```
> <WebViewLeaflet
>   ref={(component) => (this.webViewLeaflet = component)}
>   onLoad={this.onLoad}
>   eventReceiver={this}
>   mapLayers={[{
>     name: 'streets',
>     checked: 'true',
>     type: 'TileLayer',
>     baseLayer: true,
>     url: 'https://api.tiles.mapbox.com/v4/mapbox.streets/{z}/{x}/{y}.png?access_token=${MY_API_KEY}',
>   }]}
>    markers={[{
>     coords: [37.06452161, -75.67364786],
>     icon: "❤️",
>     id: 0,
>    }]}
> />
> ```
> 
> I think a reason in markers prop. When I deleted it, map works fine.

I've updated my WebViewLeaflet and changed my component to:
```
<WebViewLeaflet
  ref={(component) => (this.webViewLeaflet = component)}
  onLoad={this.onLoad}
  eventReceiver={this}
  mapLayers={[{
   name: 'streets',
   checked: 'true',
   type: 'TileLayer',
   baseLayer: true,
   url: `https://api.tiles.mapbox.com/v4/mapbox.streets/{z}/{x}/{y}.png?access_token=${MY_API_KEY}`,
  }]}
 markers={this.state.markers}
/>
```
```
componentDidMount() {
  this.getMarkers();
}

getMarkers = async () => {
  this.setState({
    markers: [
      {
        coords: [55.765543, 37.604303],
        id: 201,
        icon: "⛔"
      }
    ],
  });
}

componentDidUpdate(prevProps, prevState) {
  if (prevState.markers !== this.state.markers) {
    this.setState({
      markers: this.state.markers
    })
  }
}
```
It render map, but markers aren't visible yet.

**Comment by reggie3** [comment]
@skyflystar What version are you running?  I just posted an updated package today, so make sure you are using the most recent version.

**Comment by reggie3** [comment]
@skyflystar I don't know if it's related, but your componentDidUpdate code is confusing to me.  It's setting the state to the already current state.

Also, I've copied your marker object into the same data structures that I keep my test marker objects, and I can't seem to get it to work with your location.

**Comment by reggie3** [comment]
@skyflystar I'm not sure what's going on, but I'll keep working on it.

**Comment by skyflystar** [comment]
Hi, @reggie3 ! It's very strange, but I made this map to render markers for me. Code below:
```
    componentDidMount() {
        this.getMarkers();
    }

    getMarkers = async () => {
        await Permissions.askAsync(Permissions.LOCATION);
        let location = await Location.getCurrentPositionAsync({});
        this.setState({
            markers: [
                {
                    coords: [55.765543, 37.6043036],
                    id: 201,
                    icon: "⛔"
                }
            ],
            location,
            currentLocation: [location.coords.latitude, location.coords.longitude]
        });
    }
```
In render():
```
                <WebViewLeaflet
                    ref={(component) => (this.webViewLeaflet = component)}
                    onLoad={this.onLoad}
                    eventReceiver={this}
                    markers={this.state.markers}
                    mapLayers={[   {
                        name: 'streets',
                        type: 'TileLayer',
                        baseLayer: true,
                        url: `https://api.tiles.mapbox.com/v4/mapbox.streets/{z}/{x}/{y}.png?access_token=${MY_API_KEY}`,
                    }]}
                    ownPositionMarker={{
                        coords: this.state.currentLocation,
                        icon: '➢',
                        size: [24, 24],
                    }}
                    useMarkerClustering={true}
                />

**Comment by reggie3** [comment]
That's great!  Is there any difference between what worked, and what you did originally?  I'm not seeing anything that explains why it didn't work.
