### ISSUE TITLE
Custom animation

### ISSUE THREAD

**Issue by apndo** [reggie3/react-native-webview-leaflet#41]
Hi,
can I set a custom animation for marker? how can I make marker to play animation once, if map re-renders after moving and animation plays again?

**Comment by reggie3** [comment]
The animations are CSS key frame animations kept in the https://github.com/reggie3/react-native-webview-leaflet/blob/master/web/markers.css file.  If you can do what you want with CSS animations, then you should be able to set it as the animation for a marker.  

You can either edit the marker file yourself, send me your desired animation as a reply comment, or submit a pull request with your desired animation added to the markers.css file.
