### ISSUE TITLE
Markers vs. OwnPositionMarker 

### ISSUE THREAD

**Issue by pxFIN** [reggie3/react-native-webview-leaflet#44]
Referring to the issue https://github.com/reggie3/react-native-webview-leaflet/issues/38 i have similar challenge to render markers on openstreet map without using OwnPositionMarker

So my question is as i have understood OwnPositionMarker is required to be set for other markers to work but why ? Without setting it i get also yellow screen.

In my use case i dont have any use for OwnPositionMarker as i am rendering multiple markers based on lat/long data from external API thus i am questioning why it (ownpositionmarker) always needs to be set even its said to be Optional ?

Or maybe i am doing something wrong ?

**Comment by reggie3** [comment]
Good point.  This is a bug that needs to be addressed.

**Comment by reggie3** [comment]
I just uploaded version 4.2.4 which should fix this problem.
