### ISSUE TITLE
Expo SDK not used in react native 

### ISSUE THREAD

**Issue by ManishSharmaApporio** [reggie3/react-native-webview-leaflet#46]
Hi Team ,
I have install dependency successfully when i  run the app in device getting (expo sdk not supported) please help me out

**Comment by reggie3** [comment]
I'm not sure why you're getting this error.  I'm assuming it is because you're not using the Expo SDK.

**Comment by ManishSharmaApporio** [comment]
@reggie3 can you please let me know how can i use expo SDK in our project ?

**Comment by reggie3** [comment]
I just uploaded version 4.2.4 which should no longer require you to use Expo SDK in order to use this library.  Let me know how it goes.

If you want to use Expo, I recommend going to https://expo.io/ to learn more about it.

**Comment by ManishSharmaApporio** [comment]
@reggie3  okey  i will  let you know when its published once  on npm.
