### ISSUE TITLE
HTML not loaded in android and IOS 

### ISSUE THREAD

**Issue by ManishSharmaApporio** [reggie3/react-native-webview-leaflet#48]
![Screen Shot 2019-04-25 at 12 34 02 PM](https://user-images.githubusercontent.com/35055242/56716113-24e03580-6757-11e9-94a6-704c135f8e9a.png)

Please help me out for the same

**Comment by zxhm001** [comment]
@ManishSharmaApporio @reggie3 Anyone solved this problem?I have the same

**Comment by reggie3** [comment]
I haven't run into this problem.  What kind of device are you running into the problem on?  Maybe your browser isn't set up to run JavaScript?

**Comment by lucasvanbramer** [comment]
Having this problem on Galaxy S7.

**Comment by TimSchue** [comment]
I have the same problem.

**Comment by AsimAziz** [comment]
Same Problem.

**Comment by hussainahmad** [comment]
getting the same issue after updating expo version from `32.0.0` to `33.0.0`

**Comment by reggie3** [comment]
I think this is related to the issue that react-native-webview-cohas with running inline htm/css/javascript.  That issue is documented here https://github.com/react-native-community/react-native-webview/issues/667
