### ISSUE TITLE
VectorLayers supported?

### ISSUE THREAD

**Issue by slisystem** [reggie3/react-native-webview-leaflet#51]
Hi,

quick question: Are vector layers (especially multiple polyLines, polygons etc: https://leafletjs.com/reference-1.5.0.html#polyline) supported or can you only display HTML-based markers? If not supported yet, is it planned?

Thanks and best,
Daniel

**Comment by reggie3** [comment]
Not currently supported, though I may get around to it at some point if I find the time.

**Comment by gutoglup** [comment]
Hey, I submitted a pull request with the feature of VectorLayers inside the map. If @reggie3 can evaluate the code. :D

**Comment by zahid49** [comment]
Hi @gutoglup @reggie3,
How can I draw a circle with the latest(master) branch,  actually I'm not able to make polygons in master branch? In branch "polygons-no-expo" I was able to draw a polygon.

**Comment by gutoglup** [comment]
Hey :D @zahid49 
So, I only implements to draw vector like polygons, I don't implement to draw circles or use GeoJSON :/
But it's a great suggestion to implements.

**Comment by zahid49** [comment]
Oky, can you please help me to update. Just tell me the process .

.what are the things to setup.
.How can update dist dir.  Package is use code inside dist/index.html ?
. I need to update inside  web dir. ?

I shall be very thankful to you.
Thanks.

**Comment by zahid49** [comment]
Or can you please add a "circle" feature and please uncomment that "center button" code.

=> Add render circle feature function....
` <Circle center={layer.coords} 
              fillColor={layer.color || 'blue'} 
              radius={200}/>`

**Comment by hussainahmad** [comment]
@reggie3 is there any future release for different VectorLayers support like Polygon, Polyline

**Comment by reggie3** [comment]
I'm currently working on version 5 of the app which will support all the available geometry objects.  It also moves the package to react-native-community-webview.  I might be able to publish something this weekend.

**Comment by alainib** [comment]
hello. sorry if wrong place.
I have an array of {lat,lon} , i want to display them image like a gps trace of a car.
i think it's "polyline" but how to do it ? 
thanks

**Comment by reggie3** [comment]
Vector layers support added in version 5
