### ISSUE TITLE
Default left side layer to hide and show the map

### ISSUE THREAD

**Issue by almas542** [reggie3/react-native-webview-leaflet#53]
How can I remove at the top left that hide/show markers layer?

Also zoom control is not showing, i set the attribute to true?

i set the component like this
 <WebViewLeaflet
                    ref={(component) => (this.webViewLeaflet = component)}
                    onLoad={this.onLoad}
                    eventReceiver={this} // the component that will receive map events
                    centerPosition={this.state.mapCenterPosition}
                    zoom={this.state.zoom}
                    markers={this.state.markers}
                    showMapAttribution={true}
                    mapLayers={mapLayers}
                    showZoomControls={true}
                    // ownPositionMarker={{
                    //     coords: this.state.currentLocation,
                    //     icon: base64Image,
                    //     size: [24, 24]
                    // }}
                    // centerButton={true}
                    // useMarkerClustering={true}
                    bounds={this.state.bounds}
                    boundsOptions={{ padding: [100, 100] }}
                />

**Comment by pierroo** [comment]
Hello,

I am wondering the same; did you find a solution to hide this "ugly grey icon" at top left since?

Please let me know

**Comment by pierroo** [comment]
I'm sorry to ask again, but is there actually a way to hide this grey square at the top left of the map @reggie3 ? Or is it closed because there is no way and is meant to remain this way? Thank you for your help
