### ISSUE TITLE
this webViewLeaflet is undefined

### ISSUE THREAD

**Issue by almas542** [reggie3/react-native-webview-leaflet#54]
this code is not working 

this.webViewLeaflet.sendMessage({
  zoom: 6,
  locations: this.state.locations, // an array of locations
  showAttributionControl: this.state.mapState.showAttributionControl, // a boolean controlling whether the map displays its attribution control
  showZoomControl: this.state.mapState.showZoomControl // a boolean controlling whether the map displays its zoom control
});

**Comment by reggie3** [comment]
Where are you sending this code from, and do you actually have a reference defined?
