### ISSUE TITLE
Can it work without Expo?

### ISSUE THREAD

**Issue by pierroo** [reggie3/react-native-webview-leaflet#55]
Hi,

I read that starting version 4.2.4, we would no longer require to use Expo SDK;
which should mean we could use it in a bare react native app.

However I faced countless issue, and ended up having to install expo-asset / expo-font / expo-utils, and of course the unimodules (that is quite HEAVY in terms of actions needed)

Am I missing something?
I really do not want to go with google map which is crazy expensive when you use their maps a LOT.

Thank you for your time!

**Comment by gutoglup** [comment]
Hello, I submitted a pull request that remove the expo dependency to work with only react-native apps. ;D

**Comment by pierroo** [comment]
> Hello, I submitted a pull request that remove the expo dependency to work with only react-native apps. ;D

That is awesome @gutoglup , thank you so much for this!

I am not familiar with GitHub that much though; does that mean that if I update my version it will work?
Or does a "pull request" means it needs to be merged with the main project?

If that is the case, how can I implement your version instead?

Thank you once again so much! :)

**Comment by gutoglup** [comment]
So, in this case, we need the @reggie3 approves the pull request #58, and publish the new version to us :D

**Comment by pierroo** [comment]
Hi @gutoglup , I do not know if @reggie3 will pass by anytime soon and I respect everyone's schedule; but I really do need this pull request urgently:

is there anyway for me to fetch your version so that I can change it locally on my app while waiting for the final merge?

Again I am no GitHub expert, but I would really appreciate your help once again :)

**Comment by theinvensi** [comment]
I'm waiting this same issue be fixed...

Someone with good news? kkkk

**Comment by pierroo** [comment]
@theinvensi ; can you confirm you fetched the updated version using:

npm install --save react-native-webview-leaflet#pull/58/head

then you made the change using react-native-webview?

Then you quit your simulator and re-ran the whole app again?

**Comment by pierroo** [comment]
> So, in this case, we need the @reggie3 approves the pull request #58, and publish the new version to us :D

Hello,

Did you find any reason why we are still getting errors with your latest push?

@reggie3  can you please let us know if this project is still maintained?
I would really appreciate it so I know if I should go back to google maps, as much as I hate it and their pricing :/

**Comment by SvetlanaSiarska** [comment]
Hallo guys,  I decided to use his package react-native-webview-leaflet-without-expo-fix
Release 4.1.22 . After some hours, it works ... I mean, I can see the map in my RN simulator :)  I have  to check the other functionality now. I did two small changes on his code, but I see no possibility  to do a pull request ... this code is not on github.  Let me know, if you need help.

**Comment by reggie3** [comment]
I'm working on a new version that will only use the expo-asset-utils library for loading the index file.

**Comment by EmanueleGuidotti** [comment]
> Hallo guys, I decided to use his package react-native-webview-leaflet-without-expo-fix
> Release 4.1.22 . After some hours, it works ... I mean, I can see the map in my RN simulator :) I have to check the other functionality now. I did two small changes on his code, but I see no possibility to do a pull request ... this code is not on github. Let me know, if you need help.

Hi @SvetlanaSiarska I'd like to know where to make the changes in the code. I've tried without success.
