### ISSUE TITLE
It loads the html source code.

### ISSUE THREAD

**Issue by Nazeerahmad1996** [reggie3/react-native-webview-leaflet#56]
It loads for some time and then shows the HTML code on the screen. There nothing else. Please tell me if I am doing some error or its package error?

**Comment by kevinbraun** [comment]
Seeing the same issue myself, specifically on an Android emulator.

Running:

* Expo SDK  - 34.0.4
* react-native-webview-leaflet - 4.3.4 

Sits there loading for a while, then simply renders the content of index.html.  On a physical Android device, I don't see the HTML rendered, but the webview sits there loading indefinitely.

The same application works as expected on an iOS Simulator.

![Screen Shot 2019-08-22 at 11 53 28 AM](https://user-images.githubusercontent.com/132855/63534180-2ab31100-c4d4-11e9-8f21-6c207b6894a2.png)

**Comment by reggie3** [comment]
This happens if the react-native-community/react-native-webview package is used and is documented here: https://github.com/react-native-community/react-native-webview/issues/667 Try publishing your app.  You should be able to see the map then.
