### ISSUE TITLE
How to set the subdomains on TileLayer?

### ISSUE THREAD

**Issue by sunandy3** [reggie3/react-native-webview-leaflet#57]
I tried several ways to set the subdomains, but neither is working. What's the right way to set the subdomains for tileLayer?

const mapLayers = [
            {
                type: 'TileLayer',
                baseLayer: true,
                url: `http://webrd0{s}.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=8&x={x}&y={y}&z={z}`,
                options: {
                    subdomains: ["1", "2", "3", "4"],
                },
                subdomains: ["1", "2", "3", "4"],
                key: {
                    subdomains: ["1", "2", "3", "4"],
                },
                attribution:
                    '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            }
        ];

**Comment by sunandy3** [comment]
does anybody know the proper way to set the sub domains?

**Comment by reggie3** [comment]
That's not supported by this package.
