### ISSUE TITLE
Version 5

### ISSUE THREAD

**Issue by reggie3** [reggie3/react-native-webview-leaflet#64]
Version 5 Roadmap:
Typescript support
Fully support React Leaflet vector layers
Use new react-webview from react-native community

Version 5 is being developed in branch '15-version-5'

**Comment by reggie3** [comment]
@hussainahmad Unfortunately, those icons don't show up, and I'm not sure why that is the case.

**Comment by hussainahmad** [comment]
@reggie3  when you are going to release this master branch and npm package ?

**Comment by reggie3** [comment]
@hussainahmad that's the plan.

**Comment by reggie3** [comment]
Version 5 work moved to version/version-5 branch https://github.com/reggie3/react-native-webview-leaflet/tree/version/version-5

**Comment by reggie3** [comment]
Version 5 update on hold until I can solve this issue with my structurally similar react-native-webview-leaflet library:
https://github.com/reggie3/react-native-webview-quilljs/issues/41

**Comment by reggie3** [comment]
Version 5 released and published.
