### ISSUE TITLE
Viewport shows progress indefinitely

### ISSUE THREAD

**Issue by HasnainAD** [reggie3/react-native-webview-leaflet#66]
Hi I have just started using this library. I copied the code in README.md file with OSM layer. But I am not getting any errors instead I get following screen where the progress bar runs continuously.

![Screenshot_20191028_214843_host exp exponent](https://user-images.githubusercontent.com/10392852/67740767-c7e07780-fa38-11e9-9e59-ca1fe93d66e4.jpg)

Following is my code:

```
const mapLayers = [
   {
    name: 'OpenStreetMap',
    checked: 'true',
    type: 'TileLayer',
    baseLayer: true,
    url: `https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png`,
    attribution:
      '&amp;copy <a href=&quot;http://osm.org/copyright&quot;>OpenStreetMap</a> contributors'
  }]
```

```
<WebViewLeaflet
  ref={component => (this.webViewLeaflet = component)} 
  eventReceiver={this}  
  mapLayers={mapLayers} 
  ownPositionMarker={{
    coords: [63.250, 27.411],
    icon: "❤️",
    size: [24, 24],
    animation: {
      name: "pulse",
      duration: ".5",
      delay: 0,
      interationCount: "infinite"
    }
  }}
  centerButton={true}
  useMarkerClustering={true}
/>
```

Is this an OSM issue? Do we need to provide keys in place of s,z,x,y in url https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png?
I have gone through all issues to find no answer useful to my case.

**Comment by mvits** [comment]
Hi, 
This services not use keys, in other implementations is funtional. 

How is your package.json for this project? I have a problems in inmplement this plugin, I can't implement correctly form with basic example

**Comment by andrerim** [comment]
I have the same problem with android in development build, but the map loads if I publish the project and use the production build. Maybe the issue has something to do with permissions in development mode?

**Comment by stand1715** [comment]
same problem

**Comment by Cyf0x** [comment]
Same problem too !

**Comment by Cyf0x** [comment]
I have found this alternative. It's a little urgent on my side. I still share it with you even if it's a little off topic. It is necessary to develop a personal map with the elements you need. After that I don't know yet how I will interact between this map and my components. 

`import React, {Component} from 'react';
import {WebView} from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <WebView
        source={{uri: 'https://leafletjs.com/examples/mobile/example.html'}}
      />
    );
  }
}
`

**Comment by Cyf0x** [comment]
I have found this alternative. It's a little urgent on my side. I still share it with you even if it's a little off topic. It is necessary to develop a personal map with the elements you need. After that I don't know yet how I will interact between this map and my components.
``` import React, {Component} from 'react';
import {WebView} from 'react-native';

export default class App extends React.Component {
render() {
return (
<WebView
source={{uri: 'https://leafletjs.com/examples/mobile/example.html'}}
/>
);
}
}

**Comment by reggie3** [comment]
This issue will be addressed in version 5
