### ISSUE TITLE
Structure error package.json for implemetation this complement 

### ISSUE THREAD

**Issue by mvits** [reggie3/react-native-webview-leaflet#68]
Hi, 

I have a problems implement this complement because the dependencies versions are incompatible and errors in the implementation of basic example.

My package.json is : 

{
  "name": "App",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "expo-asset": "^4.0.0",
    "expo-constants": "^7.0.1",
    "expo-file-system": "^4.0.0",
    "expo-font": "^4.0.0",
    "leaflet": "^1.5.1",
    "react": "16.9.0",
    "react-dom": "^16.11.0",
    "react-native": "0.61.2",
    "react-native-unimodules": "^0.6.0",
    "react-native-webview-leaflet": "^4.3.4",
    "unimodules-font-interface": "^4.0.0",
    "unimodules-image-loader-interface": "^4.0.0",
    "unimodules-permissions-interface": "^4.0.0"
  },
  "devDependencies": {
    "@babel/core": "7.6.4",
    "@babel/runtime": "7.6.3",
    "@react-native-community/eslint-config": "0.0.3",
    "babel-jest": "24.9.0",
    "eslint": "^6.6.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

And App.js : 

'

import React from 'react';
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
} from 'react-native';

import {
  Header,
  LearnMoreLinks,
  Colors,
  DebugInstructions,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';

import WebViewLeaflet from 'react-native-webview-leaflet';

const App: () => React$Node = () => {
  return (
    <WebViewLeaflet
      ref={component => (this.webViewLeaflet = component)}
      // Optional: a callback that will be called when the map is loaded
      // onLoad={this.onLoad}
      // Optional: the component that will receive map events}
      // eventReceiver={this}
      // Optional: the center of the displayed map
      // centerPosition={this.state.mapCenterPosition}
      // Optional: a list of markers that will be displayed on the map
      // markers={this.state.markers}
      // Required: the map layers that will be displayed on the map. See below for a description of the map layers object
      mapLayers={mapLayers}
      // Optional: display a marker to be at a given location
      // ownPositionMarker={{
      //   coords: this.state.currentLocation,
      //   icon: '❤️',
      //   size: [24, 24],
      //   animation: {
      //     name: 'pulse',
      //     duration: '.5',
      //     delay: 0,
      //     interationCount: 'infinite',
      //   },
      // }}
      // // Optional (defaults to false): display a button that centers the map on the coordinates of ownPostionMarker. Requires that "ownPositionMarker" prop be set
      centerButton={true}
      // Optional (defaults to false): cluster icons that are in the same area
      useMarkerClustering={true}
    />
  );
};

const mapLayers = [
  {
    name: 'OpenStreetMap',
    checked: 'true',
    type: 'TileLayer',
    baseLayer: true,
    url: `https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png`,
    attribution:
      '&amp;copy <a href=&quot;http://osm.org/copyright&quot;>OpenStreetMap</a> contributors',
  },
];

export default App;
'

**Comment by reggie3** [comment]
I'm working on a new version that should hopefully address this.
