### ISSUE TITLE
expo-asset-utils needs expo-file-system to work

### ISSUE THREAD

**Issue by marcosilvestroni** [reggie3/react-native-webview-leaflet#69]
I cannot compile my project on metro and android emulator because

` [25/Nov/2019:10:45:20 +0000] "GET /index.bundle?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"
error: bundling failed: Error: Unable to resolve module `expo-file-system` from `node_modules/expo-asset-utils/src/copyAssetToSameDirectoryWithNewNameAsync.js`: expo-file-system could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31
    at Array.map (<anonymous>)
    at resolveDependencies (/home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at /home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
`

any suggestios!

Thanks

**Comment by marcosilvestroni** [comment]
I already remove node_modules and reinstall all the stuff

**Comment by reggie3** [comment]
That issue will be addressed in version 5

**Comment by varshan09** [comment]
> I cannot compile my project on metro and android emulator because
> 
> `[25/Nov/2019:10:45:20 +0000] "GET /index.bundle?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1" error: bundling failed: Error: Unable to resolve module`expo-file-system`from`node_modules/expo-asset-utils/src/copyAssetToSameDirectoryWithNewNameAsync.js`: expo-file-system could not be found within the project.
> 
> If you are sure the module exists, try these steps:
> 
> 1. Clear watchman watches: watchman watch-del-all
> 2. Delete node_modules: rm -rf node_modules and run yarn install
> 3. Reset Metro's cache: yarn start --reset-cache
> 4. Remove the cache: rm -rf /tmp/metro-*
>    at ModuleResolver.resolveDependency (/home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
>    at ResolutionRequest.resolveDependency (/home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
>    at DependencyGraph.resolveDependency (/home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
>    at Object.resolve (/home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/lib/transformHelpers.js:267:42)
>    at /home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31
>    at Array.map ()
>    at resolveDependencies (/home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
>    at /home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
>    at Generator.next ()
>    at asyncGeneratorStep (/home/marco/projects/appunto-io/caf91-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
>    `
> 
> any suggestios!
> 
> Thanks

I am facing same issue.
