### ISSUE TITLE
Is it possible to use 'ImageOverlay' with 'react-native-webview-leaflet'?

### ISSUE THREAD

**Issue by DanBrima** [reggie3/react-native-webview-leaflet#78]
Hey,
I want to use an ImageOverlay. So far I have tried:
`
<WebViewLeaflet
                ref={component => (this.webViewLeaflet = component)}
                onMessageReceived={() => {}}
                mapLayers={[
                    {
                        layerType: 'ImageOverlay',
                        url: './zooMap.png'
                    }
                ]}
            />
`

The file 'zooMap.png' is in the same folder.
Any suggestions?

**Comment by reggie3** [comment]
@DanBrima did you figure out how to do this, and if you did, would you mind sharing what you found?

**Comment by saraswathiSubbu** [comment]
Just facing with same error can anyone help me

**Comment by DanBrima** [comment]
imageOverlay = {
        layerType: MapLayerType.IMAGE_LAYER,
        url:
          'https://www.safari.co.il/Content/assets/mappage/desktop/map_zoo.png',
        bounds: [
          [-VERTICAL_AXIS / 2, -HORIZONTAL_AXIS / 2],
          [VERTICAL_AXIS / 2, HORIZONTAL_AXIS / 2],
        ],
      }

thats what worked for me. The problem was the url
