### ISSUE TITLE
Webview-Leaflet work offline?

### ISSUE THREAD

**Issue by Amaro96** [reggie3/react-native-webview-leaflet#82]
Hello, I'd like to know if it's can work offline?

**Comment by reggie3** [comment]
I don't know if it would do what you're saying.  Have you tried it yet?

**Comment by Amaro96** [comment]
Sorry for the confusion, but I would like to know if it is possible to work offline

**Comment by reggie3** [comment]
This library requires map tiles, and I don't know how to get those to work offline
