### ISSUE TITLE
Library performance

### ISSUE THREAD

**Issue by Talmaj** [reggie3/react-native-webview-leaflet#84]
I want to ask, what is the difference in terms of performance if you make the whole app online using [leaflet](https://github.com/Leaflet/Leaflet) with [react-native-webview](https://github.com/react-native-community/react-native-webview) or using this library?
It seems this library is using react-native-webview, so why not just implement the whole app in leaflet and react-native-webview?

**Comment by reggie3** [comment]
I don't know how to do what you're describing.
