### ISSUE TITLE
React native issue

### ISSUE THREAD

**Issue by schmem55** [reggie3/react-native-webview-leaflet#86]
Hi i am a newbie in react native 
i use RN 0.59.10 
i am not able to implement react-native-webview-leaflet

here is my code 

import WebViewLeaflet from "react-native-webview-leaflet";

export default function MapScreen({ navigation }) {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <WebViewLeaflet
            ref={component => (this.webViewLeaflet = component)}
            // The rest of your props, see the list below
        />
      </View>
    );
  }

here is the issue

Module `@unimodules/core` does not exist in the Haste module map

Does this package works with react native(no expo) 
thanks

**Comment by 322ne** [comment]
I,meet the same issue 。supplement， When I install  @unimodules/core, It prompts that new packages need to be installed

**Comment by 322ne** [comment]
> Hi i am a newbie in react native
> i use RN 0.59.10
> i am not able to implement react-native-webview-leaflet
> 
> here is my code
> 
> import WebViewLeaflet from "react-native-webview-leaflet";
> 
> export default function MapScreen({ navigation }) {
> return (
> <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
> <WebViewLeaflet
> ref={component => (this.webViewLeaflet = component)}
> // The rest of your props, see the list below
> />
> 
> );
> }
> 
> here is the issue
> 
> Module `@unimodules/core` does not exist in the Haste module map
> 
> Does this package works with react native(no expo)
> thanks
I opened expo-assets-utils and found that no dependencies were installed on the inside or outside. Even if I manually added the dependencies, I still get an error.

**Comment by abdulsamadola** [comment]
I'm facing the same issue, is there any work around yet?

**Comment by pavelustenko** [comment]
I facing the same issue

**Comment by reggie3** [comment]
This library uses various Expo packages to find and load files.   I don't know how they would interact with unimodules.

**Comment by ortonomy** [comment]
This package seems to be incompatible with `react-native-community/react-native-webview`, too.... 

![image](https://user-images.githubusercontent.com/6688676/85103382-20b78700-b239-11ea-80ed-d274cd054b34.png)

**Comment by reggie3** [comment]
This project hasn't been tested with unimodules, and wasn't designed to work with them.  I'll leave this issue open in case somebody figures out a way to make it work and wants to share their findings.

**Comment by ortonomy** [comment]
I don’t even know what unimodules is - it must be a dependency somewhere else. Either way, the project was working fine, I added this package and it broke.

**Comment by aristech** [comment]
check my comment [#90](https://github.com/reggie3/react-native-webview-leaflet/issues/90)
