### ISSUE TITLE
Project with path ':unimodules-core' could not be found in project ':unimodules_react-native-adapter'.

### ISSUE THREAD

**Issue by akiladevinda** [reggie3/react-native-webview-leaflet#90]
Once I installed your package It gives me some build errors. I have installed above dependencies which need to run this package

```
    "@unimodules/core": "^5.1.0",
    "@unimodules/react-native-adapter": "^5.2.0",
    "expo-font": "^8.1.1",
```

Once I do npm i -s @unimodules/react-native-adapter I cannot build my project with android

```
* Where:
Build file '/Users/akila_devinda/Desktop/PPE_Crisis_Project/Release-NoBackEnd/ppe_crisis/node_modules/@unimodules/react-native-adapter/android/build.gradle' line: 68

* What went wrong:
A problem occurred evaluating project ':unimodules_react-native-adapter'.
> Project with path ':unimodules-core' could not be found in project ':unimodules_react-native-adapter'.

```

<img width="1242" alt="Screenshot 2020-04-27 at 18 32 23" src="https://user-images.githubusercontent.com/20571997/80375158-73b63300-88b5-11ea-9856-aa2599503809.png">

**Comment by hiennguyen92** [comment]
Was anyone able to fix it?

**Comment by ortonomy** [comment]
I can't build my project as soon as I included this module in a file.... This package doesn't work any more?

**Comment by ortonomy** [comment]
possible duplicate: https://github.com/reggie3/react-native-webview-leaflet/issues/86

**Comment by ortonomy** [comment]
This project is unusable in its current state.

**Comment by akiladevinda** [comment]
@ortonomy Yes. I think we need support from the owner to resolve these issues

**Comment by aristech** [comment]
I have found a temp solution for android using react-native (not expo) by calling the html from android assets using rnfs.
Don't know if i can make a pull request since a lot of people are using this with expo
You can get from [my fork](https://github.com/aristech/react-native-webview-leaflet)

**Comment by valeriik** [comment]
Absolutely agree with @akiladevinda - unfortunately "This project is unusable in its current state."

**Comment by valeriik** [comment]
Even after installing packages that were indicated in errors:
```
"@unimodules/core": "^5.3.0",
"@unimodules/react-native-adapter": "^5.4.0",
"expo-constants": "^9.1.1",
"expo-font": "^8.2.1",
```

and insert just one this package:
```
<View>
   <WebViewLeaflet
       ref={component => (this.webViewLeaflet = component)}
      />
</View>

```

I got another error:
![image](https://user-images.githubusercontent.com/24571089/87851650-6b452580-c903-11ea-8cde-68b493759425.png)

When I commented <WebViewLeaflet this error disapeared.

So, main question still the same - HOW to run react-native-webview-leaflet?

**Comment by ZaidSA** [comment]
@reggie3 Can you please help us here, as this is making library unusable.

**Comment by ortonomy** [comment]
Honestly, it was so trivial to make a web view, with a leaflet JS full page inside that web view, there is no point in using this lib. Just roll one yourself.

**Comment by ZaidSA** [comment]
Thanks @ortonomy for your response, would you like to guide me to achieve that?

**Comment by ortonomy** [comment]
1. Create an HTML file with all the code you need to create the leaflet JS view ( make sure body is 100% high / wide using flex)
2. Make sure you load leaflet JS from CDN like js-delivr
3. Add HTML page to standard react-native community web view.
4. Done

caveat: ios and android assets are accessed differently. you'll find the answer on SO.

**Comment by ZaidSA** [comment]
Thanks very much @ortonomy, I will check that out.

**Comment by spyshower** [comment]
> I have found a temp solution for android using react-native (not expo) by calling the html from android assets using rnfs.
> Don't know if i can make a pull request since a lot of people are using this with expo
> You can get from [my fork](https://github.com/aristech/react-native-webview-leaflet)

I have checked out your repo but don't understand the installation instructions about the index file and the assets. Can you be more clear please?

**Comment by pavel-corsaghin** [comment]
> > I have found a temp solution for android using react-native (not expo) by calling the html from android assets using rnfs.
> > Don't know if i can make a pull request since a lot of people are using this with expo
> > You can get from [my fork](https://github.com/aristech/react-native-webview-leaflet)
> 
> I have checked out your repo but don't understand the installation instructions about the index file and the assets. Can you be more clear please?

I have rewritten this library using React Native CLI, react-native 0.64, react-native-webview 11.13.0. You can check here https://github.com/pavel-corsaghin/react-native-leaflet
