### ISSUE TITLE
How to remove ownPositionMarker/refresh map

### ISSUE THREAD

**Issue by davelass1** [reggie3/react-native-webview-leaflet#91]
I'm attempting to replace my ownPositionMarker with another svg string; however, it seems to add another marker. I tried to remove with passing marker as null or {}. Is there a way to remove the marker in an event fire? Second, somewhat related, if say position changes, what's the best way to update the marker position?

**Comment by DanBrima** [comment]
+1

**Comment by DanBrima** [comment]
I found a temporary solution: You can override the markers by doing:
`const newMarkers = {
      mapMarkers: [{}, {}, ...],
    };
    this.webViewLeaflet.webViewRef.injectJavaScript(
      `window.postMessage(${JSON.stringify(newMarkers)}, '*');`
    );` 

Note that it will override all the markers' not only ownPositionMarker

**Comment by davelass1** [comment]
Is there something I'm missing with the injectJavaScript function? There's an unexpected token towards the end. I edited it with ...`injectJavaScript( postMessage(JSON.stringify(newMarkers), '*'));` and get error: 

**_Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': No function was found that matched the signature provided_**

. Any chance you have a full example of this?

**Comment by DanBrima** [comment]
injectJavaScript recives a string. In addition, you forgot 'window.'
