### ISSUE TITLE
Is there a way to render Google Maps in react-native-webview-leaflet

### ISSUE THREAD

**Issue by alex-yatseyko** [reggie3/react-native-webview-leaflet#96]
I want to render Google Maps in react-native-webview-leaflet. Is there some way to do this?
I worked only with OpenStreerMaps and HereMaps

**Comment by aristech** [comment]
try this, seams to be working for me
...
const mapType = {
          HYBRID: 'y',
          SATELLITE: 's',
          TERRAIN: 'p',
          ROADMAP: 'm',
        }[extraData];
...
mapLayers={
...google
...url: `http://mt0.google.com/vt/lyrs=${mapType}&hl=en&x={x}&y={y}&z={z}&s=Ga`
}
